### ISSUE TITLE
Node with Tor connection doesn't report it's address

### ISSUE THREAD

**Issue by bayk** [NicolasFlamel1/MWC-Pay#1]
Node when connected with Tor need to send it's own Tor address to the peer.  

Please check https://github.com/mwcproject/mwc-node  for  "Message::TorAddress".  Please send this message. Otherwise peers  see your peer with address 120.0.0.1:XXXXX.  

Currently impact to your node is minor, it will not be discoverable by the MWC network.

But in future that should be considered as attack, so such connections might be banned and limited (Tor node might not send anything back if peer has loopback address). 
P.S. That future might come in a few week with a next release, so please fix the problem.

**Comment by NicolasFlamel1** [comment]
Thanks for the heads up. This is now fixed in [v1.2.1](https://github.com/NicolasFlamel1/MWC-Pay/releases/tag/v1.2.1).
